[features]
seeds = false
skip-lint = false
[programs.devnet]
contract = "BPbB2KWF6bjtjCsrFKd3buFM11ovSGWnQWohrgSfq1LU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/taoyiran/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
